/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// The `Env` interface (D1, R2, secrets) and the `cloudflare:workers` module are
// generated by `npx wrangler types` into worker-configuration.d.ts at the repo
// root. Re-run that command whenever wrangler.jsonc changes.
export {};
